version: "2"
services:
  database:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_DB=bright-db
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
    ports:
      - 5432:5432
    volumes:
      - ./dbdata:/var/lib/postgresql/data
